name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: cd server/lms && chmod +x gradlew

    - name: Spring Gradle Build Action
      uses: spring-io/spring-gradle-build-action@v2

    - name: Build with Gradle Wrapper
      run: cd server/lms && ./gradlew build

    - name: Copy file via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "server/lms/build/libs/assignment-view-0.0.1-SNAPSHOT.jar"
        target: "/home/dev/srv/spring"


