name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Add remote server to known_hosts
      run: mkdir ~/.ssh && ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: cd server/lms && chmod +x gradlew

    - name: Spring Gradle Build Action
      uses: spring-io/spring-gradle-build-action@v2

    - name: Set environment variables
      env: 
        SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
        SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

    - name: Build with Gradle Wrapper
      run: cd server/lms && ./gradlew build --info --stacktrace

    - name: List build directory
      run: ls -l server/lms/build/libs

    - name: Copy JAR File via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "server/lms/build/libs/assignment-view-0.0.1-SNAPSHOT.jar"
        target: "/home/dev/srv/spring/assignment-view-0.0.1-SNAPSHOT.jar"

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: sudo systemctl daemon-reload && sudo systemctl restart spring-boot-app


